version: '2'
services:
    inthemomentbot-app:
        image: inthemomentbot
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://inthemomentbot-postgresql:5432/inthemomentbot
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    inthemomentbot-postgresql:
        extends:
            file: postgresql.yml
            service: inthemomentbot-postgresql
